import "@/styles/globals.css";

import TopNav from "@/app/_components/TopNav";
import { Poppins } from "next/font/google";
import SidePanel from "@/app/_components/SidePanel";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "800"],
});

export const metadata = {
  title: "School-Locker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} dark h-screen overflow-hidden`}>
        <TopNav />
        <main className="relative flex h-[calc(100vh_-_56px)]">
          <SidePanel />
          {children}
        </main>
      </body>
    </html>
  );
}
